flowchart TD
    A[/Query/] --> B[Retrieval]
    B-->V[(Vector Store)]
    V --> B
    B --> k@{ shape: procs, label: "Knowledge strip" }
    k --> D
    D[Threshold] --> G[Generator]
    G --> E[/Output/]